apiVersion: v1
data:
  DB_PASSWORD: S0lBVElHRVJzODg0ODQ0IQ==
  DB_URL: amRiYzpvcmFjbGU6dGhpbjpAdmVudHVyZXdvcmxkX2hpZ2g/VE5TX0FETUlOPS9hcHAvd2FsbGV0
  DB_USERNAME: QURNSU4=
  JWT_SECRET: L2tWQ1QxUEl2dVVMR2dOU1k5SnNjN3RIcjMxVUw2Nm9xWXZSM0JVUm5Gc3VwMUlSWFZ0bEUvMSt0bURWQWJzSVVFaFB0WXV2dFdaR0FWRDh5SnFlcHc9PQ==
  SPRING_DATASOURCE_URL: amRiYzpvcmFjbGU6dGhpbjpAdmVudHVyZXdvcmxkX2hpZ2g/VE5TX0FETUlOPS9hcHAvd2FsbGV0
kind: Secret
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"DB_PASSWORD":"S0lBVElHRVJzODg0ODQ0IQ==","DB_URL":"amRiYzpvcmFjbGU6dGhpbjpAdmVudHVyZXdvcmxkX2hpZ2g/VE5TX0FETUlOPS9hcHAvd2FsbGV0","DB_USERNAME":"QURNSU4=","JWT_SECRET":"L2tWQ1QxUEl2dVVMR2dOU1k5SnNjN3RIcjMxVUw2Nm9xWXZSM0JVUm5Gc3VwMUlSWFZ0bEUvMSt0bURWQWJzSVVFaFB0WXV2dFdaR0FWRDh5SnFlcHc9PQ=="},"kind":"Secret","metadata":{"annotations":{},"name":"buyflow-secret","namespace":"buyflow"}}
  creationTimestamp: "2026-06-27T03:41:17Z"
  name: buyflow-secret
  namespace: buyflow
  resourceVersion: "1356999"
  uid: d007b60d-7a57-47e6-8bde-45fcdb952be0
type: Opaque
