apiVersion: v1
kind: Service
metadata:
  name: buyflow-backend-service
  namespace: buyflow
  labels:
    app: buyflow-backend
    app.kubernetes.io/name: buyflow-backend
    app.kubernetes.io/part-of: buyflow
spec:
  type: ClusterIP
  selector:
    app: buyflow-backend
  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP
