apiVersion: v1
kind: Service
metadata:
  name: buyflow-frontend-service
  namespace: buyflow
  labels:
    app: buyflow-frontend
    app.kubernetes.io/name: buyflow-frontend
    app.kubernetes.io/part-of: buyflow
spec:
  type: ClusterIP
  selector:
    app: buyflow-frontend
  ports:
    - name: http
      port: 3000
      targetPort: http
      protocol: TCP
