apiVersion: v1
kind: Secret
metadata:
  name: buyflow-secret
  namespace: buyflow
type: Opaque
stringData:
  DB_URL: "jdbc:oracle:thin:@ventureworld_medium?TNS_ADMIN=/app/wallet"
  DB_USERNAME: "ADMIN"
  DB_PASSWORD: "<DB_PASSWORD>"
  JWT_SECRET: "<JWT_SECRET>"
